#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
name: OTF UATS

on:
  push:
    branches:
      - main
      - GGMQ-211-codebuild
  pull_request:
    branches:
      - main
      - uat-dev

jobs:
  uat-linux:
    permissions:
      id-token: write
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-session-name: clientDeviceAuthCI
          aws-region: ${{ vars.AWS_REGION }}
      - name: Run UAT on linux
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ vars.CODE_BUILD_PROJECT_LINUX }}
          buildspec-override: uat/codebuild/uat_linux_buildspec.yaml